// LiteMQ NameServer gRPC Service Definition

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: nameserver.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	NameServerService_RegisterBroker_FullMethodName   = "/litemq.nameserver.NameServerService/RegisterBroker"
	NameServerService_UnregisterBroker_FullMethodName = "/litemq.nameserver.NameServerService/UnregisterBroker"
	NameServerService_GetRouteInfo_FullMethodName     = "/litemq.nameserver.NameServerService/GetRouteInfo"
	NameServerService_GetAllBrokers_FullMethodName    = "/litemq.nameserver.NameServerService/GetAllBrokers"
	NameServerService_Heartbeat_FullMethodName        = "/litemq.nameserver.NameServerService/Heartbeat"
)

// NameServerServiceClient is the client API for NameServerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NameServerServiceClient interface {
	// 注册Broker
	RegisterBroker(ctx context.Context, in *RegisterBrokerRequest, opts ...grpc.CallOption) (*RegisterBrokerResponse, error)
	// 注销Broker
	UnregisterBroker(ctx context.Context, in *UnregisterBrokerRequest, opts ...grpc.CallOption) (*UnregisterBrokerResponse, error)
	// 获取路由信息
	GetRouteInfo(ctx context.Context, in *GetRouteInfoRequest, opts ...grpc.CallOption) (*GetRouteInfoResponse, error)
	// 获取所有Broker
	GetAllBrokers(ctx context.Context, in *GetAllBrokersRequest, opts ...grpc.CallOption) (*GetAllBrokersResponse, error)
	// 心跳
	Heartbeat(ctx context.Context, in *BrokerHeartbeatRequest, opts ...grpc.CallOption) (*BrokerHeartbeatResponse, error)
}

type nameServerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNameServerServiceClient(cc grpc.ClientConnInterface) NameServerServiceClient {
	return &nameServerServiceClient{cc}
}

func (c *nameServerServiceClient) RegisterBroker(ctx context.Context, in *RegisterBrokerRequest, opts ...grpc.CallOption) (*RegisterBrokerResponse, error) {
	out := new(RegisterBrokerResponse)
	err := c.cc.Invoke(ctx, NameServerService_RegisterBroker_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nameServerServiceClient) UnregisterBroker(ctx context.Context, in *UnregisterBrokerRequest, opts ...grpc.CallOption) (*UnregisterBrokerResponse, error) {
	out := new(UnregisterBrokerResponse)
	err := c.cc.Invoke(ctx, NameServerService_UnregisterBroker_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nameServerServiceClient) GetRouteInfo(ctx context.Context, in *GetRouteInfoRequest, opts ...grpc.CallOption) (*GetRouteInfoResponse, error) {
	out := new(GetRouteInfoResponse)
	err := c.cc.Invoke(ctx, NameServerService_GetRouteInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nameServerServiceClient) GetAllBrokers(ctx context.Context, in *GetAllBrokersRequest, opts ...grpc.CallOption) (*GetAllBrokersResponse, error) {
	out := new(GetAllBrokersResponse)
	err := c.cc.Invoke(ctx, NameServerService_GetAllBrokers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nameServerServiceClient) Heartbeat(ctx context.Context, in *BrokerHeartbeatRequest, opts ...grpc.CallOption) (*BrokerHeartbeatResponse, error) {
	out := new(BrokerHeartbeatResponse)
	err := c.cc.Invoke(ctx, NameServerService_Heartbeat_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NameServerServiceServer is the server API for NameServerService service.
// All implementations must embed UnimplementedNameServerServiceServer
// for forward compatibility
type NameServerServiceServer interface {
	// 注册Broker
	RegisterBroker(context.Context, *RegisterBrokerRequest) (*RegisterBrokerResponse, error)
	// 注销Broker
	UnregisterBroker(context.Context, *UnregisterBrokerRequest) (*UnregisterBrokerResponse, error)
	// 获取路由信息
	GetRouteInfo(context.Context, *GetRouteInfoRequest) (*GetRouteInfoResponse, error)
	// 获取所有Broker
	GetAllBrokers(context.Context, *GetAllBrokersRequest) (*GetAllBrokersResponse, error)
	// 心跳
	Heartbeat(context.Context, *BrokerHeartbeatRequest) (*BrokerHeartbeatResponse, error)
	mustEmbedUnimplementedNameServerServiceServer()
}

// UnimplementedNameServerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNameServerServiceServer struct {
}

func (UnimplementedNameServerServiceServer) RegisterBroker(context.Context, *RegisterBrokerRequest) (*RegisterBrokerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterBroker not implemented")
}
func (UnimplementedNameServerServiceServer) UnregisterBroker(context.Context, *UnregisterBrokerRequest) (*UnregisterBrokerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterBroker not implemented")
}
func (UnimplementedNameServerServiceServer) GetRouteInfo(context.Context, *GetRouteInfoRequest) (*GetRouteInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRouteInfo not implemented")
}
func (UnimplementedNameServerServiceServer) GetAllBrokers(context.Context, *GetAllBrokersRequest) (*GetAllBrokersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllBrokers not implemented")
}
func (UnimplementedNameServerServiceServer) Heartbeat(context.Context, *BrokerHeartbeatRequest) (*BrokerHeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedNameServerServiceServer) mustEmbedUnimplementedNameServerServiceServer() {}

// UnsafeNameServerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NameServerServiceServer will
// result in compilation errors.
type UnsafeNameServerServiceServer interface {
	mustEmbedUnimplementedNameServerServiceServer()
}

func RegisterNameServerServiceServer(s grpc.ServiceRegistrar, srv NameServerServiceServer) {
	s.RegisterService(&NameServerService_ServiceDesc, srv)
}

func _NameServerService_RegisterBroker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterBrokerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NameServerServiceServer).RegisterBroker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NameServerService_RegisterBroker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NameServerServiceServer).RegisterBroker(ctx, req.(*RegisterBrokerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NameServerService_UnregisterBroker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterBrokerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NameServerServiceServer).UnregisterBroker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NameServerService_UnregisterBroker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NameServerServiceServer).UnregisterBroker(ctx, req.(*UnregisterBrokerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NameServerService_GetRouteInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRouteInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NameServerServiceServer).GetRouteInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NameServerService_GetRouteInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NameServerServiceServer).GetRouteInfo(ctx, req.(*GetRouteInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NameServerService_GetAllBrokers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllBrokersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NameServerServiceServer).GetAllBrokers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NameServerService_GetAllBrokers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NameServerServiceServer).GetAllBrokers(ctx, req.(*GetAllBrokersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NameServerService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrokerHeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NameServerServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NameServerService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NameServerServiceServer).Heartbeat(ctx, req.(*BrokerHeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NameServerService_ServiceDesc is the grpc.ServiceDesc for NameServerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NameServerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "litemq.nameserver.NameServerService",
	HandlerType: (*NameServerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterBroker",
			Handler:    _NameServerService_RegisterBroker_Handler,
		},
		{
			MethodName: "UnregisterBroker",
			Handler:    _NameServerService_UnregisterBroker_Handler,
		},
		{
			MethodName: "GetRouteInfo",
			Handler:    _NameServerService_GetRouteInfo_Handler,
		},
		{
			MethodName: "GetAllBrokers",
			Handler:    _NameServerService_GetAllBrokers_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _NameServerService_Heartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nameserver.proto",
}
