// LiteMQ Message Definition

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: message.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息类型枚举
type MessageType int32

const (
	MessageType_NORMAL      MessageType = 0
	MessageType_DELAY       MessageType = 1
	MessageType_TRANSACTION MessageType = 2
	MessageType_BROADCAST   MessageType = 3
	MessageType_ORDER       MessageType = 4
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "NORMAL",
		1: "DELAY",
		2: "TRANSACTION",
		3: "BROADCAST",
		4: "ORDER",
	}
	MessageType_value = map[string]int32{
		"NORMAL":      0,
		"DELAY":       1,
		"TRANSACTION": 2,
		"BROADCAST":   3,
		"ORDER":       4,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

// 消息状态枚举
type MessageStatus int32

const (
	MessageStatus_NORMAL_STATUS MessageStatus = 0
	MessageStatus_PREPARED      MessageStatus = 1
	MessageStatus_ROLLBACK      MessageStatus = 2
	MessageStatus_COMMIT        MessageStatus = 3
	MessageStatus_DEAD          MessageStatus = 4
)

// Enum value maps for MessageStatus.
var (
	MessageStatus_name = map[int32]string{
		0: "NORMAL_STATUS",
		1: "PREPARED",
		2: "ROLLBACK",
		3: "COMMIT",
		4: "DEAD",
	}
	MessageStatus_value = map[string]int32{
		"NORMAL_STATUS": 0,
		"PREPARED":      1,
		"ROLLBACK":      2,
		"COMMIT":        3,
		"DEAD":          4,
	}
)

func (x MessageStatus) Enum() *MessageStatus {
	p := new(MessageStatus)
	*p = x
	return p
}

func (x MessageStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[1].Descriptor()
}

func (MessageStatus) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[1]
}

func (x MessageStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageStatus.Descriptor instead.
func (MessageStatus) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

// 消费状态枚举
type ConsumeStatus int32

const (
	ConsumeStatus_SUCCESS ConsumeStatus = 0
	ConsumeStatus_RETRY   ConsumeStatus = 1
	ConsumeStatus_FAIL    ConsumeStatus = 2
)

// Enum value maps for ConsumeStatus.
var (
	ConsumeStatus_name = map[int32]string{
		0: "SUCCESS",
		1: "RETRY",
		2: "FAIL",
	}
	ConsumeStatus_value = map[string]int32{
		"SUCCESS": 0,
		"RETRY":   1,
		"FAIL":    2,
	}
)

func (x ConsumeStatus) Enum() *ConsumeStatus {
	p := new(ConsumeStatus)
	*p = x
	return p
}

func (x ConsumeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConsumeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[2].Descriptor()
}

func (ConsumeStatus) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[2]
}

func (x ConsumeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConsumeStatus.Descriptor instead.
func (ConsumeStatus) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

// 消息定义
type Message struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MessageId        string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Topic            string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Tags             []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Keys             []string               `protobuf:"bytes,4,rep,name=keys,proto3" json:"keys,omitempty"`
	Properties       map[string]string      `protobuf:"bytes,5,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body             []byte                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	MessageType      MessageType            `protobuf:"varint,7,opt,name=message_type,json=messageType,proto3,enum=litemq.common.MessageType" json:"message_type,omitempty"`
	Priority         int32                  `protobuf:"varint,8,opt,name=priority,proto3" json:"priority,omitempty"`
	Reliability      int32                  `protobuf:"varint,9,opt,name=reliability,proto3" json:"reliability,omitempty"`
	DelayTime        int64                  `protobuf:"varint,10,opt,name=delay_time,json=delayTime,proto3" json:"delay_time,omitempty"`
	TransactionId    string                 `protobuf:"bytes,11,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	MessageStatus    MessageStatus          `protobuf:"varint,12,opt,name=message_status,json=messageStatus,proto3,enum=litemq.common.MessageStatus" json:"message_status,omitempty"`
	ShardingKey      string                 `protobuf:"bytes,13,opt,name=sharding_key,json=shardingKey,proto3" json:"sharding_key,omitempty"`
	Broadcast        bool                   `protobuf:"varint,14,opt,name=broadcast,proto3" json:"broadcast,omitempty"`
	BornTimestamp    int64                  `protobuf:"varint,15,opt,name=born_timestamp,json=bornTimestamp,proto3" json:"born_timestamp,omitempty"`
	BornHost         string                 `protobuf:"bytes,16,opt,name=born_host,json=bornHost,proto3" json:"born_host,omitempty"`
	StoreHost        string                 `protobuf:"bytes,17,opt,name=store_host,json=storeHost,proto3" json:"store_host,omitempty"`
	QueueId          int32                  `protobuf:"varint,18,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	QueueOffset      int64                  `protobuf:"varint,19,opt,name=queue_offset,json=queueOffset,proto3" json:"queue_offset,omitempty"`
	CommitLogOffset  int64                  `protobuf:"varint,20,opt,name=commit_log_offset,json=commitLogOffset,proto3" json:"commit_log_offset,omitempty"`
	StoreSize        int32                  `protobuf:"varint,21,opt,name=store_size,json=storeSize,proto3" json:"store_size,omitempty"`
	StoreTimestamp   int64                  `protobuf:"varint,22,opt,name=store_timestamp,json=storeTimestamp,proto3" json:"store_timestamp,omitempty"`
	ConsumeStartTime int64                  `protobuf:"varint,23,opt,name=consume_start_time,json=consumeStartTime,proto3" json:"consume_start_time,omitempty"`
	ConsumeEndTime   int64                  `protobuf:"varint,24,opt,name=consume_end_time,json=consumeEndTime,proto3" json:"consume_end_time,omitempty"`
	ConsumeCount     int32                  `protobuf:"varint,25,opt,name=consume_count,json=consumeCount,proto3" json:"consume_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Message) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Message) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Message) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *Message) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *Message) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Message) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_NORMAL
}

func (x *Message) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Message) GetReliability() int32 {
	if x != nil {
		return x.Reliability
	}
	return 0
}

func (x *Message) GetDelayTime() int64 {
	if x != nil {
		return x.DelayTime
	}
	return 0
}

func (x *Message) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Message) GetMessageStatus() MessageStatus {
	if x != nil {
		return x.MessageStatus
	}
	return MessageStatus_NORMAL_STATUS
}

func (x *Message) GetShardingKey() string {
	if x != nil {
		return x.ShardingKey
	}
	return ""
}

func (x *Message) GetBroadcast() bool {
	if x != nil {
		return x.Broadcast
	}
	return false
}

func (x *Message) GetBornTimestamp() int64 {
	if x != nil {
		return x.BornTimestamp
	}
	return 0
}

func (x *Message) GetBornHost() string {
	if x != nil {
		return x.BornHost
	}
	return ""
}

func (x *Message) GetStoreHost() string {
	if x != nil {
		return x.StoreHost
	}
	return ""
}

func (x *Message) GetQueueId() int32 {
	if x != nil {
		return x.QueueId
	}
	return 0
}

func (x *Message) GetQueueOffset() int64 {
	if x != nil {
		return x.QueueOffset
	}
	return 0
}

func (x *Message) GetCommitLogOffset() int64 {
	if x != nil {
		return x.CommitLogOffset
	}
	return 0
}

func (x *Message) GetStoreSize() int32 {
	if x != nil {
		return x.StoreSize
	}
	return 0
}

func (x *Message) GetStoreTimestamp() int64 {
	if x != nil {
		return x.StoreTimestamp
	}
	return 0
}

func (x *Message) GetConsumeStartTime() int64 {
	if x != nil {
		return x.ConsumeStartTime
	}
	return 0
}

func (x *Message) GetConsumeEndTime() int64 {
	if x != nil {
		return x.ConsumeEndTime
	}
	return 0
}

func (x *Message) GetConsumeCount() int32 {
	if x != nil {
		return x.ConsumeCount
	}
	return 0
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\rlitemq.common\"\xdc\a\n" +
	"\aMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12\x12\n" +
	"\x04keys\x18\x04 \x03(\tR\x04keys\x12F\n" +
	"\n" +
	"properties\x18\x05 \x03(\v2&.litemq.common.Message.PropertiesEntryR\n" +
	"properties\x12\x12\n" +
	"\x04body\x18\x06 \x01(\fR\x04body\x12=\n" +
	"\fmessage_type\x18\a \x01(\x0e2\x1a.litemq.common.MessageTypeR\vmessageType\x12\x1a\n" +
	"\bpriority\x18\b \x01(\x05R\bpriority\x12 \n" +
	"\vreliability\x18\t \x01(\x05R\vreliability\x12\x1d\n" +
	"\n" +
	"delay_time\x18\n" +
	" \x01(\x03R\tdelayTime\x12%\n" +
	"\x0etransaction_id\x18\v \x01(\tR\rtransactionId\x12C\n" +
	"\x0emessage_status\x18\f \x01(\x0e2\x1c.litemq.common.MessageStatusR\rmessageStatus\x12!\n" +
	"\fsharding_key\x18\r \x01(\tR\vshardingKey\x12\x1c\n" +
	"\tbroadcast\x18\x0e \x01(\bR\tbroadcast\x12%\n" +
	"\x0eborn_timestamp\x18\x0f \x01(\x03R\rbornTimestamp\x12\x1b\n" +
	"\tborn_host\x18\x10 \x01(\tR\bbornHost\x12\x1d\n" +
	"\n" +
	"store_host\x18\x11 \x01(\tR\tstoreHost\x12\x19\n" +
	"\bqueue_id\x18\x12 \x01(\x05R\aqueueId\x12!\n" +
	"\fqueue_offset\x18\x13 \x01(\x03R\vqueueOffset\x12*\n" +
	"\x11commit_log_offset\x18\x14 \x01(\x03R\x0fcommitLogOffset\x12\x1d\n" +
	"\n" +
	"store_size\x18\x15 \x01(\x05R\tstoreSize\x12'\n" +
	"\x0fstore_timestamp\x18\x16 \x01(\x03R\x0estoreTimestamp\x12,\n" +
	"\x12consume_start_time\x18\x17 \x01(\x03R\x10consumeStartTime\x12(\n" +
	"\x10consume_end_time\x18\x18 \x01(\x03R\x0econsumeEndTime\x12#\n" +
	"\rconsume_count\x18\x19 \x01(\x05R\fconsumeCount\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*O\n" +
	"\vMessageType\x12\n" +
	"\n" +
	"\x06NORMAL\x10\x00\x12\t\n" +
	"\x05DELAY\x10\x01\x12\x0f\n" +
	"\vTRANSACTION\x10\x02\x12\r\n" +
	"\tBROADCAST\x10\x03\x12\t\n" +
	"\x05ORDER\x10\x04*T\n" +
	"\rMessageStatus\x12\x11\n" +
	"\rNORMAL_STATUS\x10\x00\x12\f\n" +
	"\bPREPARED\x10\x01\x12\f\n" +
	"\bROLLBACK\x10\x02\x12\n" +
	"\n" +
	"\x06COMMIT\x10\x03\x12\b\n" +
	"\x04DEAD\x10\x04*1\n" +
	"\rConsumeStatus\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\t\n" +
	"\x05RETRY\x10\x01\x12\b\n" +
	"\x04FAIL\x10\x02B\x12Z\x10litemq/api/protob\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_message_proto_goTypes = []any{
	(MessageType)(0),   // 0: litemq.common.MessageType
	(MessageStatus)(0), // 1: litemq.common.MessageStatus
	(ConsumeStatus)(0), // 2: litemq.common.ConsumeStatus
	(*Message)(nil),    // 3: litemq.common.Message
	nil,                // 4: litemq.common.Message.PropertiesEntry
}
var file_message_proto_depIdxs = []int32{
	4, // 0: litemq.common.Message.properties:type_name -> litemq.common.Message.PropertiesEntry
	0, // 1: litemq.common.Message.message_type:type_name -> litemq.common.MessageType
	1, // 2: litemq.common.Message.message_status:type_name -> litemq.common.MessageStatus
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		EnumInfos:         file_message_proto_enumTypes,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
