// LiteMQ NameServer gRPC Service Definition

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: nameserver.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 注册Broker请求
type RegisterBrokerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrokerId      string                 `protobuf:"bytes,1,opt,name=broker_id,json=brokerId,proto3" json:"broker_id,omitempty"`
	BrokerName    string                 `protobuf:"bytes,2,opt,name=broker_name,json=brokerName,proto3" json:"broker_name,omitempty"`
	BrokerAddr    string                 `protobuf:"bytes,3,opt,name=broker_addr,json=brokerAddr,proto3" json:"broker_addr,omitempty"`
	ClusterName   string                 `protobuf:"bytes,4,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"` // master, slave
	Topics        map[string]*QueueIds   `protobuf:"bytes,6,rep,name=topics,proto3" json:"topics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterBrokerRequest) Reset() {
	*x = RegisterBrokerRequest{}
	mi := &file_nameserver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterBrokerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterBrokerRequest) ProtoMessage() {}

func (x *RegisterBrokerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nameserver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterBrokerRequest.ProtoReflect.Descriptor instead.
func (*RegisterBrokerRequest) Descriptor() ([]byte, []int) {
	return file_nameserver_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterBrokerRequest) GetBrokerId() string {
	if x != nil {
		return x.BrokerId
	}
	return ""
}

func (x *RegisterBrokerRequest) GetBrokerName() string {
	if x != nil {
		return x.BrokerName
	}
	return ""
}

func (x *RegisterBrokerRequest) GetBrokerAddr() string {
	if x != nil {
		return x.BrokerAddr
	}
	return ""
}

func (x *RegisterBrokerRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *RegisterBrokerRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *RegisterBrokerRequest) GetTopics() map[string]*QueueIds {
	if x != nil {
		return x.Topics
	}
	return nil
}

// 队列ID列表
type QueueIds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueIds      []int32                `protobuf:"varint,1,rep,packed,name=queue_ids,json=queueIds,proto3" json:"queue_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueIds) Reset() {
	*x = QueueIds{}
	mi := &file_nameserver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueIds) ProtoMessage() {}

func (x *QueueIds) ProtoReflect() protoreflect.Message {
	mi := &file_nameserver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueIds.ProtoReflect.Descriptor instead.
func (*QueueIds) Descriptor() ([]byte, []int) {
	return file_nameserver_proto_rawDescGZIP(), []int{1}
}

func (x *QueueIds) GetQueueIds() []int32 {
	if x != nil {
		return x.QueueIds
	}
	return nil
}

// 注册Broker响应
type RegisterBrokerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterBrokerResponse) Reset() {
	*x = RegisterBrokerResponse{}
	mi := &file_nameserver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterBrokerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterBrokerResponse) ProtoMessage() {}

func (x *RegisterBrokerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nameserver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterBrokerResponse.ProtoReflect.Descriptor instead.
func (*RegisterBrokerResponse) Descriptor() ([]byte, []int) {
	return file_nameserver_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterBrokerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterBrokerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 注销Broker请求
type UnregisterBrokerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrokerId      string                 `protobuf:"bytes,1,opt,name=broker_id,json=brokerId,proto3" json:"broker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterBrokerRequest) Reset() {
	*x = UnregisterBrokerRequest{}
	mi := &file_nameserver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterBrokerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterBrokerRequest) ProtoMessage() {}

func (x *UnregisterBrokerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nameserver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterBrokerRequest.ProtoReflect.Descriptor instead.
func (*UnregisterBrokerRequest) Descriptor() ([]byte, []int) {
	return file_nameserver_proto_rawDescGZIP(), []int{3}
}

func (x *UnregisterBrokerRequest) GetBrokerId() string {
	if x != nil {
		return x.BrokerId
	}
	return ""
}

// 注销Broker响应
type UnregisterBrokerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterBrokerResponse) Reset() {
	*x = UnregisterBrokerResponse{}
	mi := &file_nameserver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterBrokerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterBrokerResponse) ProtoMessage() {}

func (x *UnregisterBrokerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nameserver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterBrokerResponse.ProtoReflect.Descriptor instead.
func (*UnregisterBrokerResponse) Descriptor() ([]byte, []int) {
	return file_nameserver_proto_rawDescGZIP(), []int{4}
}

func (x *UnregisterBrokerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnregisterBrokerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 获取路由信息请求
type GetRouteInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRouteInfoRequest) Reset() {
	*x = GetRouteInfoRequest{}
	mi := &file_nameserver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRouteInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRouteInfoRequest) ProtoMessage() {}

func (x *GetRouteInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nameserver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRouteInfoRequest.ProtoReflect.Descriptor instead.
func (*GetRouteInfoRequest) Descriptor() ([]byte, []int) {
	return file_nameserver_proto_rawDescGZIP(), []int{5}
}

func (x *GetRouteInfoRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

// 获取路由信息响应
type GetRouteInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouteInfo     *TopicRouteInfo        `protobuf:"bytes,1,opt,name=route_info,json=routeInfo,proto3" json:"route_info,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRouteInfoResponse) Reset() {
	*x = GetRouteInfoResponse{}
	mi := &file_nameserver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRouteInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRouteInfoResponse) ProtoMessage() {}

func (x *GetRouteInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nameserver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRouteInfoResponse.ProtoReflect.Descriptor instead.
func (*GetRouteInfoResponse) Descriptor() ([]byte, []int) {
	return file_nameserver_proto_rawDescGZIP(), []int{6}
}

func (x *GetRouteInfoResponse) GetRouteInfo() *TopicRouteInfo {
	if x != nil {
		return x.RouteInfo
	}
	return nil
}

func (x *GetRouteInfoResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 主题路由信息
type TopicRouteInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicName     string                 `protobuf:"bytes,1,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	QueueCount    int32                  `protobuf:"varint,2,opt,name=queue_count,json=queueCount,proto3" json:"queue_count,omitempty"`
	BrokerAddrs   []string               `protobuf:"bytes,3,rep,name=broker_addrs,json=brokerAddrs,proto3" json:"broker_addrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicRouteInfo) Reset() {
	*x = TopicRouteInfo{}
	mi := &file_nameserver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicRouteInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicRouteInfo) ProtoMessage() {}

func (x *TopicRouteInfo) ProtoReflect() protoreflect.Message {
	mi := &file_nameserver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicRouteInfo.ProtoReflect.Descriptor instead.
func (*TopicRouteInfo) Descriptor() ([]byte, []int) {
	return file_nameserver_proto_rawDescGZIP(), []int{7}
}

func (x *TopicRouteInfo) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

func (x *TopicRouteInfo) GetQueueCount() int32 {
	if x != nil {
		return x.QueueCount
	}
	return 0
}

func (x *TopicRouteInfo) GetBrokerAddrs() []string {
	if x != nil {
		return x.BrokerAddrs
	}
	return nil
}

// 获取所有Broker请求
type GetAllBrokersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllBrokersRequest) Reset() {
	*x = GetAllBrokersRequest{}
	mi := &file_nameserver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllBrokersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllBrokersRequest) ProtoMessage() {}

func (x *GetAllBrokersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nameserver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllBrokersRequest.ProtoReflect.Descriptor instead.
func (*GetAllBrokersRequest) Descriptor() ([]byte, []int) {
	return file_nameserver_proto_rawDescGZIP(), []int{8}
}

// 获取所有Broker响应
type GetAllBrokersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brokers       []*BrokerInfo          `protobuf:"bytes,1,rep,name=brokers,proto3" json:"brokers,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllBrokersResponse) Reset() {
	*x = GetAllBrokersResponse{}
	mi := &file_nameserver_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllBrokersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllBrokersResponse) ProtoMessage() {}

func (x *GetAllBrokersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nameserver_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllBrokersResponse.ProtoReflect.Descriptor instead.
func (*GetAllBrokersResponse) Descriptor() ([]byte, []int) {
	return file_nameserver_proto_rawDescGZIP(), []int{9}
}

func (x *GetAllBrokersResponse) GetBrokers() []*BrokerInfo {
	if x != nil {
		return x.Brokers
	}
	return nil
}

func (x *GetAllBrokersResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Broker信息
type BrokerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrokerId      string                 `protobuf:"bytes,1,opt,name=broker_id,json=brokerId,proto3" json:"broker_id,omitempty"`
	BrokerName    string                 `protobuf:"bytes,2,opt,name=broker_name,json=brokerName,proto3" json:"broker_name,omitempty"`
	BrokerAddr    string                 `protobuf:"bytes,3,opt,name=broker_addr,json=brokerAddr,proto3" json:"broker_addr,omitempty"`
	ClusterName   string                 `protobuf:"bytes,4,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	LastUpdate    int64                  `protobuf:"varint,6,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	Topics        map[string]*QueueIds   `protobuf:"bytes,7,rep,name=topics,proto3" json:"topics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrokerInfo) Reset() {
	*x = BrokerInfo{}
	mi := &file_nameserver_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrokerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokerInfo) ProtoMessage() {}

func (x *BrokerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_nameserver_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokerInfo.ProtoReflect.Descriptor instead.
func (*BrokerInfo) Descriptor() ([]byte, []int) {
	return file_nameserver_proto_rawDescGZIP(), []int{10}
}

func (x *BrokerInfo) GetBrokerId() string {
	if x != nil {
		return x.BrokerId
	}
	return ""
}

func (x *BrokerInfo) GetBrokerName() string {
	if x != nil {
		return x.BrokerName
	}
	return ""
}

func (x *BrokerInfo) GetBrokerAddr() string {
	if x != nil {
		return x.BrokerAddr
	}
	return ""
}

func (x *BrokerInfo) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *BrokerInfo) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *BrokerInfo) GetLastUpdate() int64 {
	if x != nil {
		return x.LastUpdate
	}
	return 0
}

func (x *BrokerInfo) GetTopics() map[string]*QueueIds {
	if x != nil {
		return x.Topics
	}
	return nil
}

// Broker心跳请求
type BrokerHeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrokerId      string                 `protobuf:"bytes,1,opt,name=broker_id,json=brokerId,proto3" json:"broker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrokerHeartbeatRequest) Reset() {
	*x = BrokerHeartbeatRequest{}
	mi := &file_nameserver_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrokerHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokerHeartbeatRequest) ProtoMessage() {}

func (x *BrokerHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nameserver_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokerHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*BrokerHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_nameserver_proto_rawDescGZIP(), []int{11}
}

func (x *BrokerHeartbeatRequest) GetBrokerId() string {
	if x != nil {
		return x.BrokerId
	}
	return ""
}

// Broker心跳响应
type BrokerHeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrokerHeartbeatResponse) Reset() {
	*x = BrokerHeartbeatResponse{}
	mi := &file_nameserver_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrokerHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokerHeartbeatResponse) ProtoMessage() {}

func (x *BrokerHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nameserver_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokerHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*BrokerHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_nameserver_proto_rawDescGZIP(), []int{12}
}

func (x *BrokerHeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BrokerHeartbeatResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_nameserver_proto protoreflect.FileDescriptor

const file_nameserver_proto_rawDesc = "" +
	"\n" +
	"\x10nameserver.proto\x12\x11litemq.nameserver\"\xd3\x02\n" +
	"\x15RegisterBrokerRequest\x12\x1b\n" +
	"\tbroker_id\x18\x01 \x01(\tR\bbrokerId\x12\x1f\n" +
	"\vbroker_name\x18\x02 \x01(\tR\n" +
	"brokerName\x12\x1f\n" +
	"\vbroker_addr\x18\x03 \x01(\tR\n" +
	"brokerAddr\x12!\n" +
	"\fcluster_name\x18\x04 \x01(\tR\vclusterName\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12L\n" +
	"\x06topics\x18\x06 \x03(\v24.litemq.nameserver.RegisterBrokerRequest.TopicsEntryR\x06topics\x1aV\n" +
	"\vTopicsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.litemq.nameserver.QueueIdsR\x05value:\x028\x01\"'\n" +
	"\bQueueIds\x12\x1b\n" +
	"\tqueue_ids\x18\x01 \x03(\x05R\bqueueIds\"H\n" +
	"\x16RegisterBrokerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"6\n" +
	"\x17UnregisterBrokerRequest\x12\x1b\n" +
	"\tbroker_id\x18\x01 \x01(\tR\bbrokerId\"J\n" +
	"\x18UnregisterBrokerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"+\n" +
	"\x13GetRouteInfoRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\"n\n" +
	"\x14GetRouteInfoResponse\x12@\n" +
	"\n" +
	"route_info\x18\x01 \x01(\v2!.litemq.nameserver.TopicRouteInfoR\trouteInfo\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"s\n" +
	"\x0eTopicRouteInfo\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x01 \x01(\tR\ttopicName\x12\x1f\n" +
	"\vqueue_count\x18\x02 \x01(\x05R\n" +
	"queueCount\x12!\n" +
	"\fbroker_addrs\x18\x03 \x03(\tR\vbrokerAddrs\"\x16\n" +
	"\x14GetAllBrokersRequest\"f\n" +
	"\x15GetAllBrokersResponse\x127\n" +
	"\abrokers\x18\x01 \x03(\v2\x1d.litemq.nameserver.BrokerInfoR\abrokers\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xde\x02\n" +
	"\n" +
	"BrokerInfo\x12\x1b\n" +
	"\tbroker_id\x18\x01 \x01(\tR\bbrokerId\x12\x1f\n" +
	"\vbroker_name\x18\x02 \x01(\tR\n" +
	"brokerName\x12\x1f\n" +
	"\vbroker_addr\x18\x03 \x01(\tR\n" +
	"brokerAddr\x12!\n" +
	"\fcluster_name\x18\x04 \x01(\tR\vclusterName\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12\x1f\n" +
	"\vlast_update\x18\x06 \x01(\x03R\n" +
	"lastUpdate\x12A\n" +
	"\x06topics\x18\a \x03(\v2).litemq.nameserver.BrokerInfo.TopicsEntryR\x06topics\x1aV\n" +
	"\vTopicsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.litemq.nameserver.QueueIdsR\x05value:\x028\x01\"5\n" +
	"\x16BrokerHeartbeatRequest\x12\x1b\n" +
	"\tbroker_id\x18\x01 \x01(\tR\bbrokerId\"I\n" +
	"\x17BrokerHeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\x90\x04\n" +
	"\x11NameServerService\x12e\n" +
	"\x0eRegisterBroker\x12(.litemq.nameserver.RegisterBrokerRequest\x1a).litemq.nameserver.RegisterBrokerResponse\x12k\n" +
	"\x10UnregisterBroker\x12*.litemq.nameserver.UnregisterBrokerRequest\x1a+.litemq.nameserver.UnregisterBrokerResponse\x12_\n" +
	"\fGetRouteInfo\x12&.litemq.nameserver.GetRouteInfoRequest\x1a'.litemq.nameserver.GetRouteInfoResponse\x12b\n" +
	"\rGetAllBrokers\x12'.litemq.nameserver.GetAllBrokersRequest\x1a(.litemq.nameserver.GetAllBrokersResponse\x12b\n" +
	"\tHeartbeat\x12).litemq.nameserver.BrokerHeartbeatRequest\x1a*.litemq.nameserver.BrokerHeartbeatResponseB\x12Z\x10litemq/api/protob\x06proto3"

var (
	file_nameserver_proto_rawDescOnce sync.Once
	file_nameserver_proto_rawDescData []byte
)

func file_nameserver_proto_rawDescGZIP() []byte {
	file_nameserver_proto_rawDescOnce.Do(func() {
		file_nameserver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nameserver_proto_rawDesc), len(file_nameserver_proto_rawDesc)))
	})
	return file_nameserver_proto_rawDescData
}

var file_nameserver_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_nameserver_proto_goTypes = []any{
	(*RegisterBrokerRequest)(nil),    // 0: litemq.nameserver.RegisterBrokerRequest
	(*QueueIds)(nil),                 // 1: litemq.nameserver.QueueIds
	(*RegisterBrokerResponse)(nil),   // 2: litemq.nameserver.RegisterBrokerResponse
	(*UnregisterBrokerRequest)(nil),  // 3: litemq.nameserver.UnregisterBrokerRequest
	(*UnregisterBrokerResponse)(nil), // 4: litemq.nameserver.UnregisterBrokerResponse
	(*GetRouteInfoRequest)(nil),      // 5: litemq.nameserver.GetRouteInfoRequest
	(*GetRouteInfoResponse)(nil),     // 6: litemq.nameserver.GetRouteInfoResponse
	(*TopicRouteInfo)(nil),           // 7: litemq.nameserver.TopicRouteInfo
	(*GetAllBrokersRequest)(nil),     // 8: litemq.nameserver.GetAllBrokersRequest
	(*GetAllBrokersResponse)(nil),    // 9: litemq.nameserver.GetAllBrokersResponse
	(*BrokerInfo)(nil),               // 10: litemq.nameserver.BrokerInfo
	(*BrokerHeartbeatRequest)(nil),   // 11: litemq.nameserver.BrokerHeartbeatRequest
	(*BrokerHeartbeatResponse)(nil),  // 12: litemq.nameserver.BrokerHeartbeatResponse
	nil,                              // 13: litemq.nameserver.RegisterBrokerRequest.TopicsEntry
	nil,                              // 14: litemq.nameserver.BrokerInfo.TopicsEntry
}
var file_nameserver_proto_depIdxs = []int32{
	13, // 0: litemq.nameserver.RegisterBrokerRequest.topics:type_name -> litemq.nameserver.RegisterBrokerRequest.TopicsEntry
	7,  // 1: litemq.nameserver.GetRouteInfoResponse.route_info:type_name -> litemq.nameserver.TopicRouteInfo
	10, // 2: litemq.nameserver.GetAllBrokersResponse.brokers:type_name -> litemq.nameserver.BrokerInfo
	14, // 3: litemq.nameserver.BrokerInfo.topics:type_name -> litemq.nameserver.BrokerInfo.TopicsEntry
	1,  // 4: litemq.nameserver.RegisterBrokerRequest.TopicsEntry.value:type_name -> litemq.nameserver.QueueIds
	1,  // 5: litemq.nameserver.BrokerInfo.TopicsEntry.value:type_name -> litemq.nameserver.QueueIds
	0,  // 6: litemq.nameserver.NameServerService.RegisterBroker:input_type -> litemq.nameserver.RegisterBrokerRequest
	3,  // 7: litemq.nameserver.NameServerService.UnregisterBroker:input_type -> litemq.nameserver.UnregisterBrokerRequest
	5,  // 8: litemq.nameserver.NameServerService.GetRouteInfo:input_type -> litemq.nameserver.GetRouteInfoRequest
	8,  // 9: litemq.nameserver.NameServerService.GetAllBrokers:input_type -> litemq.nameserver.GetAllBrokersRequest
	11, // 10: litemq.nameserver.NameServerService.Heartbeat:input_type -> litemq.nameserver.BrokerHeartbeatRequest
	2,  // 11: litemq.nameserver.NameServerService.RegisterBroker:output_type -> litemq.nameserver.RegisterBrokerResponse
	4,  // 12: litemq.nameserver.NameServerService.UnregisterBroker:output_type -> litemq.nameserver.UnregisterBrokerResponse
	6,  // 13: litemq.nameserver.NameServerService.GetRouteInfo:output_type -> litemq.nameserver.GetRouteInfoResponse
	9,  // 14: litemq.nameserver.NameServerService.GetAllBrokers:output_type -> litemq.nameserver.GetAllBrokersResponse
	12, // 15: litemq.nameserver.NameServerService.Heartbeat:output_type -> litemq.nameserver.BrokerHeartbeatResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_nameserver_proto_init() }
func file_nameserver_proto_init() {
	if File_nameserver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nameserver_proto_rawDesc), len(file_nameserver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nameserver_proto_goTypes,
		DependencyIndexes: file_nameserver_proto_depIdxs,
		MessageInfos:      file_nameserver_proto_msgTypes,
	}.Build()
	File_nameserver_proto = out.File
	file_nameserver_proto_goTypes = nil
	file_nameserver_proto_depIdxs = nil
}
